import Container from "react-bootstrap/Container";

export const metadata = {
    title: "LLDMAll | Mi perfil",
    description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
    return (
        <Container fluid>
            {children}
        </Container>
    );
}
