import Container from "react-bootstrap/Container";

export const metadata = {
    title: "LLDMAll | Inicio",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <Container fluid>
            {children}
        </Container>
    );
}
