import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./global.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import Container from "react-bootstrap/Container";
import MyNavbar from "./MyNavbar"
import Footer from "./Footer";
import Sidebar from "./Sidebar";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

export const metadata = {
  title: "LLDMAll | Inicio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" data-bs-theme="light">
      <body className={inter.className}>
        <Container fluid>
          <MyNavbar />

          <Row className="mt-4">
            <Col lg={3}>
              <Sidebar />
            </Col>

            <Col lg={9}>
              {children}
            </Col>

            <Col lg={12}>
              <Footer />
            </Col>
          </Row>

        </Container>
      </body>
    </html>
  );
}
