import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import Container from "react-bootstrap/Container";

export const metadata = {
  title: "LLDMAll",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container fluid>{children}</Container>
      </body>
    </html>
  );
}
