import Container from "react-bootstrap/Container";

export const metadata = {
    title: "LLDMAll | klk",
    description: "Generated by create next app",
};

export default function Layout({ children }) {
    return (
        <Container fluid>{children}</Container>
    );
}
