import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import Sidebar from "../../Components/Sidebar";

export const metadata = {
  title: "LLDMAll | Promovamos el autocunsumo",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <Container fluid>

      {/* Second Row */}
      <Row className="mt-4">
        <Col lg={3}>
          <Sidebar />
        </Col>

        <Col lg={9}>
          {children}
        </Col>
      </Row>
    </Container>
  );
}
