import 'react-bootstrap-typeahead/css/Typeahead.css';
import Footer from "@/app/Components/Footer";
import Container from "react-bootstrap/Container"
import Row from "react-bootstrap/Row"
import Card from "react-bootstrap/Card"
import Col from "react-bootstrap/Col"
import JoinHeader from "@/app/Components/JoinHeader";

export const metadata = {
    title: "LLDMAll | Productos",
    description: "Generated by create next app",
};

export default async function DashboardLayout({ children }) {
    return (
        <>{children}</>
    );
}
